### ISSUE TITLE
Another couple of ideas :-)

### ISSUE THREAD

**Issue by Grey-Lancaster** [widapro/wledPixel#4]
#1 Would it be hard to keep everything scrolling.  Like "Mary had a little lamb:?

#2 If that is possible, be able to add text before or after the mqtt value.  "Outside Temperature is" mqtt

**Comment by widapro** [comment]
Answering question #2 
In my opinion, it is easier to add a prefix in HA during sending a message. Try to use this in your HA automation:
``` 
action:
  service: mqtt.publish
  data_template:
    payload_template: "{{trigger.to_state.state}} Your_Prefix"
    topic: meat/1
```

in my HA I use this:

```
action:
  service: mqtt.publish
  data:
    topic: testTopic1
    payload_template: "{{states('sensor.lumi_lumi_weather_40c2e307_temperature_2')}} C"
```
